from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, HttpUrl, field_validator

class AnalyzeRequest(BaseModel):
    """
    Request payload containing the public GitHub URL to analyze.
    """
    github_url: str = Field(
        ..., 
        description="Public GitHub repository URL (e.g., https://github.com/owner/repo)",
        examples=["https://github.com/fastapi/fastapi"]
    )

    @field_validator("github_url")
    @classmethod
    def validate_github_url(cls, value: str) -> str:
        """
        Validates basic GitHub URL structure.
        """
        cleaned = value.strip().rstrip("/")
        if cleaned.endswith(".git"):
            cleaned = cleaned[:-4]
            
        # Basic validation pattern matching github.com domain
        pattern = r"^https?://(?:www\.)?github\.com/[a-zA-Z0-9_\-\.]+/[a-zA-Z0-9_\-\.]+$"
        import re
        if not re.match(pattern, cleaned):
            raise ValueError("Must be a valid public GitHub repository URL (https://github.com/owner/repo)")
        return value

class AnalyzeResponse(BaseModel):
    """
    Response acknowledging the queued analysis.
    """
    report_id: str = Field(..., description="Unique UUID for tracking the analysis report")
    status: str = Field(..., description="Current status of the analysis job")
    message: str = Field(..., description="Actionable summary status message")

class LargestFileSchema(BaseModel):
    path: str
    extension: str
    size: int
    line_count: int

class LatencySchema(BaseModel):
    clone_time: float
    analyze_time: float
    indexing_time: float
    total_time: float

class MetricsSchema(BaseModel):
    total_files: int
    total_lines: int
    largest_files: List[LargestFileSchema]
    latency: Optional[LatencySchema] = None

class LanguageDetailsSchema(BaseModel):
    files: int
    lines: int
    percentage: float

class EntryPointSchema(BaseModel):
    path: str
    language: str
    description: str
    confidence: float

class DependencyItemSchema(BaseModel):
    name: str
    version: str
    scope: str

class ReportResponse(BaseModel):
    """
    Complete analysis details return schema.
    """
    id: str
    github_url: str
    repo_owner: Optional[str] = None
    repo_name: Optional[str] = None
    status: str
    error_message: Optional[str] = None
    metrics: Optional[MetricsSchema] = None
    languages: Optional[Dict[str, LanguageDetailsSchema]] = None
    frameworks: Optional[Dict[str, float]] = None
    entry_points: Optional[List[EntryPointSchema]] = None
    dependencies: Optional[Dict[str, List[DependencyItemSchema]]] = None
    summary: Optional[Dict[str, Any]] = None
    architecture_report: Optional[Dict[str, Any]] = None
    important_files: Optional[List[Dict[str, Any]]] = None
    onboarding_guide: Optional[Dict[str, Any]] = None
    created_at: datetime
    updated_at: datetime

    model_config = {
        "from_attributes": True  # Enables direct mapping from SQLAlchemy instances (Pydantic v2 style)
    }

class AskRequest(BaseModel):
    question: str = Field(..., description="Developer question about the repository", examples=["How does authentication work?"])

class CitationSchema(BaseModel):
    file_path: str = Field(..., description="Relpath of the cited file")
    start_line: int = Field(..., description="Starting line of the cited section")
    end_line: int = Field(..., description="Ending line of the cited section")

class AskResponse(BaseModel):
    answer: str = Field(..., description="Grounded answer from the repository context")
    citations: List[CitationSchema] = Field(default=[], description="Source citations referenced in the answer")
    confidence_score: str = Field(default="High", description="Confidence evaluation (High|Medium|Low)")
    confidence_explanation: str = Field(default="Answer is grounded in direct code citations.", description="Explanation of confidence evaluation")

class TourStepSchema(BaseModel):
    step: int = Field(..., description="Step index")
    file: str = Field(..., description="Target file path")
    reason: str = Field(..., description="Why this step is important")

class TourResponse(BaseModel):
    tour_steps: List[TourStepSchema] = Field(default=[], description="Sequential codebase tour steps")
    raw_text: str = Field(..., description="Raw text generated by LLM")

class WalkthroughResponse(BaseModel):
    walkthrough: str = Field(..., description="Markdown architecture walkthrough guide")

class NodeSchema(BaseModel):
    id: str = Field(..., description="Unique path identifier for the node")
    label: str = Field(..., description="Short display label for the node")
    type: str = Field(..., description="Node classification (entrypoint, router, service, database)")

class EdgeSchema(BaseModel):
    source: str = Field(..., description="ID of source node")
    target: str = Field(..., description="ID of target node")
    label: str = Field(..., description="Connection relationship description")

class GraphResponse(BaseModel):
    nodes: List[NodeSchema] = Field(default=[], description="List of graph nodes")
    edges: List[EdgeSchema] = Field(default=[], description="List of directed edges")

class ExplanationResponse(BaseModel):
    purpose: str = Field(..., description="Plain-English purpose definition")
    responsibilities: List[str] = Field(default=[], description="Bullet points of key duties")
    key_functions: List[str] = Field(default=[], description="List of main classes, functions, or files")
    dependencies: List[str] = Field(default=[], description="List of modules or packages imported")
    related_paths: List[str] = Field(default=[], description="Closely coupled code paths")
    developer_value: str = Field(..., description="Developer context needed before modifying this asset")

